# Requires
# - GitHub pages are enabled
# - GitHub pages are configured for the gh-pages branch
name: Lint to the Future Dashboard

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    uses: mansona/lint-to-the-future-dashboard-action/.github/workflows/dashboard.yml@main
    with:
      folder: ''
