exclude:
  - "app/assets/stylesheets/common/foundation/**"
  - "app/assets/stylesheets/desktop/magnific-popup.scss"
  - "app/assets/stylesheets/mobile/magnific-popup.scss"
  - "app/assets/stylesheets/vendor/**"

linters:
  StringQuotes:
    enabled: false
  Indentation:
    width: 2
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  SelectorDepth:
    enabled: false
  CapitalizationInSelector:
    enabled: false
  NameFormat:
    enabled: false
  UrlFormat:
    enabled: false
  BorderZero:
    enabled: false
  Shorthand:
    enabled: false
  PropertySortOrder:
    enabled: false
  DuplicateProperty:
  # Excludes required because of false positives with rgba fallbacks
    exclude:
      - "app/assets/stylesheets/desktop/modal.scss"
      - "app/assets/stylesheets/mobile/modal.scss"
      - "app/assets/stylesheets/mobile/topic-list.scss"
  SingleLinePerSelector:
    enabled: false
  HexFormat:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  ColorKeyword:
    enabled: false
  DeclarationOrder:
    enabled: false
  TrailingSemicolonAfterPropertyValue:
    enabled: false
  IdWithExtraneousSelector:
    enabled: false
  PlaceholderInExtend:
    enabled: false
