exclude:
  - "app/assets/stylesheets/common/foundation/**"
  - "app/assets/stylesheets/desktop/magnific-popup.scss"
  - "app/assets/stylesheets/mobile/magnific-popup.scss"
  - "app/assets/stylesheets/vendor/**"

linters:
  StringQuotes:
    style: double_quotes
  Indentation:
    width: 2
  Comment:
    exclude:
      - "app/assets/stylesheets/desktop/code_highlighting.scss"
      - "test/stylesheets/test_helper.css"
  LeadingZero:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  SelectorDepth:
    enabled: false
  CapitalizationInSelector:
    enabled: false
  NameFormat:
    enabled: false
  PropertySortOrder:
    enabled: false
  DuplicateProperty:
  # Excludes required because of false positives with rgba fallbacks
    exclude:
      - "app/assets/stylesheets/desktop/modal.scss"
      - "app/assets/stylesheets/mobile/modal.scss"
      - "app/assets/stylesheets/mobile/topic-list.scss"
  SingleLinePerSelector:
    enabled: false
  HexFormat:
    enabled: false
  SpaceBeforeBrace:
    allow_single_line_padding: true
  ColorKeyword:
    enabled: false
  DeclarationOrder:
    enabled: false
  IdWithExtraneousSelector:
    enabled: false
  PlaceholderInExtend:
    # Used for clearfix extending
    enabled: false
