---
default_dark_mode_color_scheme_id: '1'
download_remote_images_to_local: 'false'
default_trust_level: '1'
allowed_iframes: https://www.google.com/maps/embed?|https://www.openstreetmap.org/export/embed.html?|https://calendar.google.com/calendar/embed?|https://codepen.io/|https://www.instagram.com|http://localhost:3000/discobot/certificate.svg
default_sidebar_categories: 2|3|4
default_composer_category: '4'
default_email_digest_frequency: '1440'
siwe_json_rpc: 5|https://rpc.ankr.com/eth_goerli
plural_polis_site_id: polis_site_id_4Tp2Drcqld0prEyR5j
styleguide_enabled: 'true'
