packages:
  - "admin"
  - "bootstrap-json"
  - "dialog-holder"
  - "discourse"
  - "discourse-common"
  - "discourse-hbr"
  - "discourse-plugins"
  - "discourse-widget-hbs"
  - "ember-cli-progress-ci"
  - "ember-production-deprecations"
  - "pretty-text"
  - "select-kit"
  - "truth-helpers"
  - "wizard"
