name: Ember Version Enforcement

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Yarn install
        run: |
          cd app/assets/javascripts/discourse
          yarn install
      - name: "Check ember version"
        working-directory: app/assets/javascripts/discourse
        run: |
          node -e '
            const version = require("ember-source/package.json").version;
            console.log("Ember version is", version);
            if(version.split(".")[0] !== 3){
              console.log(`Ember has unexpectedly been upgraded to version ${version}. If this is intentional, remove this github workflow.`);
              process.exit(1);
            }
          '
