name: Licenses

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: licenses-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    if: github.event_name == 'pull_request' || github.repository != 'discourse/discourse-private-mirror'
    name: run
    runs-on: debian-12
    container: discourse/discourse_test:release
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: bundle install
        run: |
          cp -r /var/www/discourse/vendor/bundle ./vendor/bundle
          gem install bundler --conservative -v $(awk '/BUNDLED WITH/ { getline; gsub(/ /,""); print $0 }' Gemfile.lock)
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs $(($(nproc) > 4 ? 4 : $(nproc) - 1))
          bundle clean

      - name: Setup licensed
        run: |
          gem install licensed

      - name: Check RubyGems Licenses
        if: ${{ !cancelled() }}
        run: |
          licensed cache
          licensed status

      - name: pnpm install
        run: pnpm install

      - name: Check JS Licenses
        if: ${{ !cancelled() }}
        run: |
          pnpm licensee --errors-only
