name: Linting

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: linting-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    container: discourse/discourse_test:slim
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: Bundler cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Setup gems
        run: |
          gem install bundler --conservative -v $(awk '/BUNDLED WITH/ { getline; gsub(/ /,""); print $0 }' Gemfile.lock)
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs 4
          bundle clean

      - name: Get pnpm cache directory
        id: node-cache-dir
        run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Node cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: ${{ steps.node-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: pnpm install
        run: pnpm install

      - name: Rubocop
        if: ${{ !cancelled() }}
        run: bundle exec rubocop --parallel .

      - name: ESLint (core)
        if: ${{ !cancelled() }}
        run: pnpm eslint app/assets/javascripts

      - name: ESLint (core plugins)
        if: ${{ !cancelled() }}
        run: pnpm eslint plugins

      - name: Prettier
        if: ${{ !cancelled() }}
        run: |
          pnpm prettier -v
          pnpm pprettier --list-different \
            "app/assets/stylesheets/**/*.scss" \
            "app/assets/javascripts/**/*.js" \
            "plugins/**/assets/stylesheets/**/*.scss" \
            "plugins/**/assets/javascripts/**/*.js"

      - name: Ember template lint
        if: ${{ !cancelled() }}
        run: |
          pnpm ember-template-lint \
            --no-error-on-unmatched-pattern \
            "app/assets/javascripts/**/*.hbs" \
            "plugins/**/assets/javascripts/**/*.hbs"

      - name: English locale lint (core)
        if: ${{ !cancelled() }}
        run: bundle exec ruby script/i18n_lint.rb "config/**/locales/{client,server}.en.yml"

      - name: English locale lint (core plugins)
        if: ${{ !cancelled() }}
        run: bundle exec ruby script/i18n_lint.rb "plugins/**/locales/{client,server}.en.yml"
