name: Smoke Test
   
on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - 'tests-passed'
    
jobs:
  smoke_test:
    name: "smoke test"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install unbuffer
        run: sudo apt-get install -yqq expect

      - name: Boot dev image
        run: unbuffer d/boot_dev

      - name: Create script
        run: | 
          touch tmp/script.rb
          echo "User.create!(username:'smoke_user', password:'P4ssw0rd', admin:true)" >> tmp/script.rb
          echo "SiteSetting.wizard_enabled = false" >> tmp/script.rb

      - name: tmp
        run: sudo chown -R 1000:1000 .

      - name: Bundle
        run: unbuffer d/bundle install

      - name: Migrate
        run: unbuffer d/rake db:migrate

      - name: Run script
        run: unbuffer d/rails runner tmp/script.rb

      - name: Start Server
        run: unbuffer d/rails s &

      - name: Run smoke test
        run: unbuffer d/rake smoke:test

      - name: Zip Screenshots
        if: failure()
        run: sudo zip -r smoke-test-screenshots.zip tmp/smoke-test-screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: smoke-test-screenshots
          path: smoke-test-screenshots.zip

