name: Tests

on:
  pull_request:
    paths-ignore:
      - "migrations/**"
  push:
    branches:
      - main
      - beta
      - stable
    paths-ignore:
      - "migrations/**"

concurrency:
  group: tests-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # build:
  #   runs-on: 'ubuntu-20.04-8core'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Build and export
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./.github/test-image
  #         build-args: |
  #           github_sha=${{ github.sha }}
  #         tags: myimage:latest
  #         cache-to: type=gha,mode=min,scope=${{github.run_id}}

  use:
    runs-on: 'ubuntu-20.04-8core'
    # needs: build
    defaults:
      run:
        shell: bash -eo pipefail -c "cat {0} | docker exec -w /var/www/discourse myimage bash --noprofile --norc -eo pipefail"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ./.github/test-image
          build-args: |
            github_sha=${{ github.sha }}
          tags: myimage:latest
          cache-from: type=gha,scope=${{github.run_id}}
          load: true
      - name: Start image
        shell: bash # On host
        run: docker run --entrypoint /bin/bash --rm --name myimage myimage:latest tail -f /dev/null
      - name: Run tests
        run: rails runner 'puts "Hello world"'


